/** One-tap prompts for PO tests. Each chip sends exactly this text. */
export const TEST_PROMPTS = [
  'Hallo Jarvis.',
  'Wer bist du und wer bin ich?',
  'Ich heiße Max und trinke gerne Kaffee.',
  'Was trinke ich?',
  'Wie ist mein Name?',
  'Milch auf die Einkaufsliste',
  'auch Brot',
  'was fehlt?',
  'Milch hab ich',
  'Milch kaufen',
  'Was steht an?',
  'Guten Morgen',
  '/hilfe',
  'Fernseher an',
  'Sag Hallo und duze mich.',
  'Erklären Sie in einem Satz, was Sie tun.',
  'Notiz: WLAN steht am Router',
  'Zeige Notizen',
  'Suche im Internet nach Kuchenrezepten',
  'in 20 Minuten Milch',
  'morgen 8 Uhr Steuer',
  'Wetter heute',
  'Wetter morgen in München',
  'und morgen?',
  'Brauche ich einen Schirm?',
  'Was soll ich anziehen?',
  'Timer 8 Minuten Nudeln',
  'Wecker 7 Uhr',
  'Wecker 7 Uhr jeden Tag',
  'jeden Tag 8 Uhr Tabletten',
  'Temperatur hier',
  'Termin morgen 15 Uhr Zahnarzt',
  'Termin morgen 15 Uhr Zahnarzt Bahnhofstraße',
  'Wann muss ich zum Zahnarzt los?',
  'Kalender',
  'Freundin wohnt in Heilbronn',
  'Fahr mich zur Freundin',
  'Freundin, Tel 01711234567',
  'Ruf die Freundin an',
  'Lauf zur Freundin',
  'Wenn ich zuhause bin Müll raus',
  'Ich bin zuhause',
  'Lies das Foto',
  'Aktiviere Fahrmodus',
  'Lautstärke 50',
  'lauter um 10',
  'Fahrmodus aus',
  'Mama hat am 3. März Geburtstag',
  'Jeden Dienstag Müll',
  'was kommt diese Woche raus?',
  'das zweite',
  'Wann hatte ich das mit der Steuer?',
] as const
