/** One-tap prompts for PO tests. Each chip sends exactly this text. */
export const TEST_PROMPTS = [
  'Hallo Jarvis.',
  'Wer bist du und wer bin ich?',
  'Ich heiße Max und trinke gerne Kaffee.',
  'Was trinke ich?',
  'Was trinke ich gerne?',
  'Wie ist mein Name?',
  'Milch auf die Einkaufsliste',
  'auch Brot',
  'was fehlt?',
  'Milch hab ich',
  'Milch kaufen',
  'Was steht an?',
  'Guten Morgen',
  '/hilfe',
  'Fernseher an',
  'Fire TV',
  'Öffne Netflix',
  'Spiel Dune Film',
  'Spiele ein YouTube Video auf dem Fernseher',
  'Ventilator an',
  'Sag Hallo und duze mich.',
  'Erklären Sie in einem Satz, was Sie tun.',
  'Notiz: WLAN steht am Router',
  'Zeige Notizen',
  'Suche im Internet nach Kuchenrezepten',
  'Suche nach Küchengeräte',
  'Beste Preise Staubsauger',
  'Öffnen CarPlay',
  'in 20 Minuten Milch',
  'in 20 Minuten Milch holen',
  'morgen 8 Uhr Steuer',
  'Wetter heute',
  'Wetter morgen in München',
  'und morgen?',
  'Brauche ich einen Schirm?',
  'Was soll ich anziehen?',
  'Timer 8 Minuten Nudeln',
  'Wecker 7 Uhr',
  'Wecker 7 Uhr jeden Tag',
  'jeden Tag 8 Uhr Tabletten',
  'Temperatur hier',
  'Termin morgen 15 Uhr Zahnarzt',
  'Termin morgen 15 Uhr Zahnarzt Bahnhofstraße',
  'Wann muss ich zum Zahnarzt los?',
  'Kalender',
  'Freundin wohnt in Heilbronn',
  'Nach Heilbronn',
  'Fahr mich zur Freundin',
  'Freundin, Tel 01711234567',
  'Ruf die Freundin an',
  'Lauf zur Freundin',
  'Wenn ich zuhause bin Müll raus',
  'Ich bin zuhause',
  'Lies das Foto',
  'Aktiviere Fahrmodus',
  'Zeig Spotify',
  'Spiel das auf Spotify',
  'Lautstärke 50',
  'lauter um 10',
  'Fahrmodus aus',
  'Mama hat am 3. März Geburtstag',
  'Jeden Dienstag Müll',
  'was kommt diese Woche raus?',
  'das zweite',
  'Wann hatte ich das mit der Steuer?',
  'Was kommt heute?',
  'Milch fehlt',
  'Ventilator Stufe zwei',
  'Timer acht Minuten Nudeln',
  'Spiel mal was Nettes',
  'Ich fahre gerne Auto',
  'kein Kaffee mehr',
  'Netflix an',
  'Fahr mich zu einer Tanke',
  'Wo bin ich gerade?',
  'Carplay',
  'Öffne das overlay',
  'Aktiviere das overlay',
  'Gib mir ne Route',
  'wo könnte ich jetzt frühstücken',
  'Wie weit noch',
  'nächste Apotheke',
  'nächster pol',
  'Fahr zur Arbeit',
  'Ich arbeite in Stuttgart',
  'Wie voll ist der Akku',
  'Ruf mal die Freundin',
  'Schreib der Freundin ich bin in 10 Minuten',
  'Wo läuft Dune kostenlos',
  'Wie gut ist Dune',
  'IMDb Dune',
  'Rabatt-Suche an',
  'Hat die Apotheke auf',
  'nächster Laden',
  'Bro anrufen',
  'Nachricht an Bro ich bin da',
  'FIFA starten',
  'Was siehst du auf dem PC',
  'Züge anklicken',
  'Wie ist die Luft?',
  'Wann Sonnenaufgang?',
  'Mit der Bahn nach Heilbronn',
  'Nachrichten',
  'Was ist heute in Ingesheim passiert',
  'Ist heute Feiertag?',
  'Wie viele Scheibenwischer verkauft Valeo am tag',
  'Steckdose an',
  'alle Steckdosen aus',
  'Wie spät ist es?',
  'weißt du wie viel Uhr es ist',
  'weißt du wo ich bin',
  'wo könnte ich denn sein',
  'Was ist der bip in Deutschland',
  'Kannst du den bip von Deutschland in einer Tabelle darstellen?',
  'Taschenlampe an',
  'ohne meine Adresse nachzugucken weißt du wo ich bin',
  'Nach Ingersheim',
  'Kaufmodus',
  'Kaufmodus aus',
  'Kaufmodus schließen',
  'Öffne den Kaufmodus',
  'Öffne Kaufmodus',
  'Ich will einkaufen',
  'einkaufen',
  'Shopping-Modus',
  'Such mir einen Fernseher',
  'Ich brauche neue Kopfhörer',
  'Ich brauche einen Gaming-Monitor unter 300 Euro',
  'Ich brauche einen Laptop',
  'Such mir Milch im Angebot',
  'Such Angebote für Monitor',
  'Wo bekomme ich einen Monitor',
  'Wo bekomme ich diesen Fernseher heute in der Nähe?',
  'Nur Angebote für Kaffee unter 5 €',
  'Zeig mir alle aktuellen Angebote für Waschmittel',
  'Prospekt von Aldi',
  'Werbung von Lidl',
  'Vergleiche diese drei Fernseher',
  'Such günstigere Alternativen',
  'Pack Nummer 2 auf die Einkaufsliste',
  'Pack Milch auf die Einkaufsliste',
  'Milch holen',
  'Was muss ich einkaufen',
  'Einkaufsliste leeren',
  'Gibt’s Unwetter?',
  'Gibt es Unwetter?',
  'DWD Warnung',
  'Wetterwarnung',
  'Sind in BW Ferien?',
  'Schulferien in Bayern',
  'Ferien in Hessen',
  'Was ist der Dollar?',
  'Euro in Dollar',
  'Wechselkurs',
  'Kurs von Dollar',
  'Was ist das für ein Produkt?',
  'Nutri-Score',
  'Barcode',
  'Was ist das für ein Buch?',
  'Wer schrieb Faust',
  'Wie hat der VfB gespielt?',
  'Ergebnis Bayern',
  'Ergebnis Dortmund',
  'Bundesliga',
  'Was ist das für eine Pflanze?',
  'Welches Kraut ist das?',
  'Mondphase',
  'Wann fliegt die ISS?',
  'Internationale Raumstation',
  'Welcher Vogel ist das?',
  'Was für ein Tier ist das?',
  'iNaturalist',
  'Was fliegt da?',
  'Flugzeug über uns',
  'OpenSky',
  'Kündigungsfrist Wohnung',
  'Mietrecht',
  'Was bedeutet die Waschschüssel?',
  'Waschsymbol',
  'Bügelsymbol',
  'Fleck auf dem Hemd',
  'Wie viele Schritte heute?',
  'Luftdruck',
  'Barometer',
  'Kompass',
  'Nordrichtung',
  'Schach e2e4',
  'Schach neu',
  'Schach reset',
  'Schach Stellung',
  'Schach',
  'Taschenlampe aus',
  'Öffne WLAN',
  'Öffne Bluetooth',
  'Nicht stören',
  'Wie ist die Verbindung',
  'Standort aktivieren',
  'es ist 06:30 Uhr wo könnte ich denn sein',
  'nächster Bäcker',
  'nächstes Café',
  'CarPlay aus',
  'Aktiviere CarPlay',
  'Fahrmodus',
  'Zeig die Karte',
  'Restweg',
  'Wann bin ich da',
  'Timer 0 Minuten',
  'in 20 Minuten',
  'Fahr nach Atlantis',
  'Licht an',
  'Alexa, Licht an',
  'Tapo Steckdose an',
  'Kopple die Tuya Cloud',
  'Verbinde Apple CarPlay',
  'Schreib Mama auf WhatsApp ich bin unterwegs',
  'Stopp',
  'Wecker 25 Uhr',
] as const
