/** One-tap prompts for PO tests. Each chip sends exactly this text. */
export const TEST_PROMPTS = [
  'Hallo Jarvis.',
  'Wer bist du und wer bin ich?',
  'Ich heiße Max und trinke gerne Kaffee.',
  'Was trinke ich?',
  'Was trinke ich gerne?',
  'Wie ist mein Name?',
  'Milch auf die Einkaufsliste',
  'auch Brot',
  'was fehlt?',
  'Milch hab ich',
  'Milch kaufen',
  'Was steht an?',
  'Guten Morgen',
  '/hilfe',
  'Fernseher an',
  'Fire TV',
  'Öffne Netflix',
  'Spiel Dune Film',
  'Spiele ein YouTube Video auf dem Fernseher',
  'Ventilator an',
  'Sag Hallo und duze mich.',
  'Erklären Sie in einem Satz, was Sie tun.',
  'Notiz: WLAN steht am Router',
  'Zeige Notizen',
  'Suche im Internet nach Kuchenrezepten',
  'Suche nach Küchengeräte',
  'Beste Preise Staubsauger',
  'Öffnen CarPlay',
  'in 20 Minuten Milch',
  'in 20 Minuten Milch holen',
  'morgen 8 Uhr Steuer',
  'Wetter heute',
  'Wetter morgen in München',
  'und morgen?',
  'Brauche ich einen Schirm?',
  'Was soll ich anziehen?',
  'Timer 8 Minuten Nudeln',
  'Wecker 7 Uhr',
  'Wecker 7 Uhr jeden Tag',
  'jeden Tag 8 Uhr Tabletten',
  'Temperatur hier',
  'Termin morgen 15 Uhr Zahnarzt',
  'Termin morgen 15 Uhr Zahnarzt Bahnhofstraße',
  'erstell einen Termin für den 5.9. 2026, 15:00 Uhr Zahnarzt',
  'was steht heute so an?',
  'was steht diese Woche an?',
  'was steht die nächsten 3 Tage an?',
  'Wann muss ich zum Zahnarzt los?',
  'Kalender',
  'Freundin wohnt in Heilbronn',
  'Nach Heilbronn',
  'Fahr mich zur Freundin',
  'Freundin, Tel 01711234567',
  'Ruf die Freundin an',
  'Lauf zur Freundin',
  'Wenn ich zuhause bin Müll raus',
  'Ich bin zuhause',
  'Lies das Foto',
  'Aktiviere Fahrmodus',
  'Zeig Spotify',
  'Spiel das auf Spotify',
  'Lautstärke 50',
  'lauter um 10',
  'Fahrmodus aus',
  'Mama hat am 3. März Geburtstag',
  'Jeden Dienstag Müll',
  'was kommt diese Woche raus?',
  'das zweite',
  'Wann hatte ich das mit der Steuer?',
  'Was kommt heute?',
  'Milch fehlt',
  'Ventilator Stufe zwei',
  'Timer acht Minuten Nudeln',
  'Spiel mal was Nettes',
  'Ich fahre gerne Auto',
  'kein Kaffee mehr',
  'Netflix an',
  'Fahr mich zu einer Tanke',
  'Wo bin ich gerade?',
  'Carplay',
  'Öffne das overlay',
  'Öffne das watchlist overlay',
  'WHOIS example.com',
  'Zeig Kameras',
  'Aktiviere das overlay',
  'Gib mir ne Route',
  'wo könnte ich jetzt frühstücken',
  'Wie weit noch',
  'nächste Apotheke',
  'nächster pol',
  'Fahr zur Arbeit',
  'Ich arbeite in Stuttgart',
  'Wie voll ist der Akku',
  'Ruf mal die Freundin',
  'Schreib der Freundin ich bin in 10 Minuten',
  'Wo läuft Dune kostenlos',
  'Wie gut ist Dune',
  'IMDb Dune',
  'Rabatt-Suche an',
  'Hat die Apotheke auf',
  'nächster Laden',
  'Bro anrufen',
  'Nachricht an Bro ich bin da',
  'FIFA starten',
  'Was siehst du auf dem PC',
  'Züge anklicken',
  'Wie ist die Luft?',
  'Wann Sonnenaufgang?',
  'Mit der Bahn nach Heilbronn',
  'Nachrichten',
  'Was ist heute in Ingesheim passiert',
  'Ist heute Feiertag?',
  'Wie viele Scheibenwischer verkauft Valeo am tag',
  'Steckdose an',
  'alle Steckdosen aus',
  'Wie spät ist es?',
  'weißt du wie viel Uhr es ist',
  'weißt du wo ich bin',
  'wo könnte ich denn sein',
  'Was ist der bip in Deutschland',
  'Kannst du den bip von Deutschland in einer Tabelle darstellen?',
  'Taschenlampe an',
  'ohne meine Adresse nachzugucken weißt du wo ich bin',
  'Nach Ingersheim',
  'Was ist die Weltlage?',
  'Warum steigt der Ölpreis?',
  'Wird Benzin teurer?',
  'Fällt der Dollar?',
  'Fällt SAP morgen?',
  'Was ist der Dollar?',
  'Bar in der Nähe',
  'nächste Kneipe',
  'bestell ein Taxi',
  'Sprachnachricht an Mama ich bin in 10 Minuten',
  'Todo: Testdebug Milch',
  'Gibt es Unwetter?',
  'Wo ist die ISS?',
  'Körper an',
  'zeig mal den körper',
  'Kugel an',
  'Wo liegt Berlin',
  'klick das Captcha',
  'Friday',
  'Was steht am Freitag an?',
  'Darf ich im Park grillen?',
  'Wo ist Speichern',
  'Lage an',
  'Zeig mir London',
  'Was ist das für eine Stadt?',
  'Was sehe ich?',
  'Zeig mir Atlantis',
  'zoom auf Tokio',
  'Was kannst du?',
  'Bist du ChatGPT?',
  'Kannst du Bilder malen?',
  'Spiele Musik',
  'Schreib mir eine E-Mail',
  'Zeig mir die Nachrichten',
  'Überweise 200 Euro',
  'Zeig Street View von London',
  'Hilfe',
  'Rufe 112',
  'mach die weltkugel an',
  'Was ist heute so auf der Welt passiert',
  'Zeig New York',
  'Was is das für ne Stadt',
  'Körper an und Zeig London',
  'Mach Live-Satellitenvideo an',
  'Wo ist London',
  'Lage aus',
  'Muss man Eintritt zahlen für Venedig',
  'Wo liegt Kiew',
  'Gibt es Blitzer?',
  'Baustellen auf der Strecke',
  'Spiel Amazon Music',
  'Leg den Chat in Arbeit',
  'Chat-Ordner',
  'Sag Bescheid wenn Instanudeln im Angebot sind',
  'Instanudeln',
  'Preiswache aus',
  'Was weißt du über den Zahnarzt',
  'Wo stand das mit der Steuer',
  'Wie wird das Wetter?',
  'Öffne CarPlay',
  // 18.0.3 — Screenshot-Bugs und der Tiefenprüfung-Nachzug. Ohne diese
  // Chips bleibt der Router auf den alten 181 Sätzen grün und fährt trotzdem nach Tschechien.
  'Lidl',
  'nächster Lidl',
  'Fahr zum Lidl',
  'Aldi',
  'nächster Aldi',
  'Rewe',
  'Penny',
  'Netto',
  'Edeka',
  'nächster Lidl bitte',
  'zum Lidl',
  'Lidl in der Nähe',
  'nächster Rewe',
  'nächster Penny',
  'Kaufland',
  'nächster Kaufland',
  'dm',
  'nächster dm',
  'Rossmann',
  'nächster Aldi Süd',
  'nächste Apotheke bitte',
  'Lass uns Schach spielen',
  'Schach',
  'Zeig mir das Schachbrett',
  'das Schachbrett',
  'Bauer e2 e4',
  'Dame e2 e4',
  'Läufer e8 f9',
  'Springer g1 f3',
  'Turm a1 a8',
  'König e1 e2',
  'e2 e4',
  'E2 e4',
  'Spiel Schach',
  'Las uns Schach spielen',
  'wollen wir Schach spielen',
  'Schachbrett',
  'neues Schach',
  'Schach neu',
  'Wie steht die Bundesliga?',
  'Wie steht die 2. Bundesliga?',
  'Wie steht die zweite Bundesliga?',
  'Wie steht die 2. Liga?',
  'Wie hat der VfB gespielt?',
  'Bundesliga Tabelle',
  'Zeig die Bundesliga Tabelle',
  'Was kostet E10 an der nächsten Tankstelle',
  'nächste Tankstelle',
  'Regnet es gleich?',
  'Wetter die nächsten drei Tage',
  'Luftqualität',
  'Sonnenuntergang',
  'Wie warm wird es',
  'Taschenlampe aus',
  'Taschenlampe',
  'WLAN an',
  'Bluetooth an',
  'Nicht stören',
  'Spotify Pause',
  'Spotify weiter',
  'Lautstärke leiser',
  'Nachrichten heute',
  'Was steht in den Nachrichten',
  'Unwetterwarnung',
  'Zeig Erdbeben',
  'Zeig Waldbrände',
  'Wo brennt es',
  'ISS über uns',
  'Mondphase',
  'Was fliegt da',
  'Blitzer auf der Strecke',
  'Baustelle',
  'Kalender heute',
  'Termin absagen',
  'weck mich in zehn Minuten',
  'Ventilator aus',
  'PC testen',
  'PC koppeln',
  'TV aus',
  'YouTube am Fernseher',
  'Amazon Prime am Fernseher',
  'Körper aus',
  'Kugel aus',
  'Wo liegt Paris',
  'Wo liegt Tokio',
  'Wer bin ich',
  'Was mag ich',
  'vergiss meinen Namen',
  'Einkaufsliste',
  'Butter auf die Liste',
  'Eier kaufen',
  'Mit der Bahn nach Stuttgart',
  'Zug nach München',
  'bestell ein Uber',
  'Rufe Mama an',
  'SMS an Papa ich komm später',
  'Freundin anrufen',
  'Nach Hause',
  'Fahr nach Hause',
  'Wie lange noch',
  'Wahlergebnis',
  'Wer hat die Wahl gewonnen?',
  'Wecker aus',
  'Timer stopp',
  'Stopp Timer',
  'Öffne Watchliste',
  'Öffne Lieblinge',
  'Zeig Chat',
  'Zeig Lage',
  'Öffne Einstellungen Musik',
  'Einstellungen zu',
  'Research an',
  'Mach WLAN aus',
  'Termin Freitag 10 Uhr Teammeeting',
  'Timer 1 Minute Tee',
  'Käse auf die Liste',
  'Zeig Filme',
  'Kalender zu',
  'Entferne alle Erinnerungen am 22. September',
  'Änder Maxi Geburtstag in Jakob Geburtstag',
  'Maxi Geburtstag heißt jetzt Jakob Geburtstag',
  'Zeig Flugzeuge',
  'Zeig Satelliten',
  'Watchliste: Dune',
  'Nee auf die lieblingsliste',
  'Samstag Geburtstag Jakob 18 Uhr',
  'Verschieb Jakob auf Sonntag 19 Uhr',
] as const
