/**
 * Ein Satz pro Katalog-Agent. Quelle für Gold, Prompt-Slices und den Sweep-Test.
 * PRE_ROUTER (llm/help/research/…) gehört nicht hierher.
 */
export const AGENT_SWEEP: Record<string, string> = {
  wont: 'Mach ein Foto',
  identity: 'Bist du ChatGPT?',
  tv: 'Fernseher an',
  film: 'Wie gut ist Dune',
  watchlist: 'Watchliste: Dune',
  osint: 'WHOIS example.com',
  fan: 'Ventilator an',
  plug: 'Steckdose an',
  here: 'Wo bin ich gerade?',
  fuel: 'nächste Tankstelle',
  poi: 'nächster Lidl',
  transit: 'Mit der Bahn nach Stuttgart',
  drive: 'Öffne CarPlay',
  device: 'Taschenlampe an',
  pc: 'FIFA starten',
  maps: 'Freundin wohnt in Heilbronn',
  teach: 'Lern das als Fachwissen FritzBox-Doku: Das WLAN-Passwort steht unter dem Router, nicht im Chat.',
  pack: 'Fachwissen FritzBox',
  memory: 'Ich heiße Max und trinke gerne Kaffee.',
  shopping: 'Milch auf die Einkaufsliste',
  birthday: 'Mama hat am 3. März Geburtstag',
  home: 'Wenn ich zuhause bin Müll raus',
  leave: 'Wann muss ich zum Zahnarzt los?',
  brief: 'Was steht an?',
  holiday: 'Ist heute Feiertag?',
  calendar: 'Termin morgen 15 Uhr Zahnarzt',
  alarm: 'Wecker 7 Uhr',
  timer: 'Timer 8 Minuten Nudeln',
  reminder: 'in 20 Minuten Milch',
  todo: 'Todo: Testdebug Milch',
  idea: 'Idee: Körper und Chat gleichzeitig',
  desk: 'Schreibtisch an',
  eye: 'Lies das Foto',
  doc: 'Lies das PDF',
  weather: 'Wetter heute',
  news: 'Nachrichten',
  search: 'Wann hatte ich das mit der Steuer?',
  warn: 'Gibt es Unwetter?',
  blitzer: 'Gibt es Blitzer?',
  'chat-folder': 'Leg den Chat in Arbeit',
  'watch-price': 'Sag Bescheid wenn Instanudeln im Angebot sind',
  amazon: 'Spiel Amazon Music',
  recall: 'Was weißt du über den Zahnarzt',
  ferien: 'Wann sind die Schulferien in Baden-Württemberg?',
  fx: 'Was ist der Dollar?',
  food: 'Zutaten von Nutella',
  library: 'Wer schrieb Der Prozess?',
  sport: 'Wie steht die Bundesliga?',
  sky: 'Wo ist die ISS?',
  nature: 'welche Pflanze ist das: Gänseblümchen',
  flights: 'Was fliegt da',
  law: 'Darf ich im Park grillen?',
  haushalt: 'Was bedeutet Waschschüssel 40?',
  sensors: 'Wie viele Schritte',
  chess: 'Lass uns Schach spielen',
  hud: 'Kugel an',
  trace: 'Was ist traceroute',
  digest: 'Fass das Gespräch zusammen',
  outlook: 'Was ist die Weltlage?',
  taxi: 'bestell ein Taxi',
  backup: 'Hausstand exportieren',
  face: 'Friday',
  app: 'Zeig Chat',
}
